# Generated by Django 3.0 on 2021-11-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('face_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
    ]
